execute 'source ' . vimrc_path . '/autoload/pathogen.vim'
call pathogen#infect(vimrc_path . '/bundle')


" Put plugins and dictionaries in this dir (also on Windows)
let vimDir = '$HOME/.vim'
let &runtimepath.=','.vimDir

" Keep undo history across sessions by storing it in a file
if has('persistent_undo')
    let myUndoDir = expand(vimDir . '/undodir')
    " Create dirs
    call system('mkdir ' . vimDir)
    call system('mkdir ' . myUndoDir)
    let &undodir = myUndoDir
    set undofile
endif

set nocompatible
let mapleader=","
set modelines=0
set encoding=utf-8


source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction


:set tabstop=4
:set shiftwidth=4
:set expandtab
:set nobackup
:set guifont=Courier_New:h9:cANSI
:let g:p4ClientRoot = 'c:/dev/ws/perforce'
:let g:p4PromptToCheckout = 1
:let g:p4CheckOutDefault = 1
runtime perforce/perforceutils.vim
runtime perforce/perforcemenu.vim

:set cmdheight=2
" paj using PSCP on Windows. Works best with Pageant.
if ($OS =~ "Windows")
  let g:netrw_cygwin= 0
  let g:netrw_scp_cmd="c:\\bin\\pscp.exe -q -batch"
  let g:ackprg="perl c:\\bin\\ack.pl -H --nocolor --nogroup --column"
  au GUIEnter * simalt ~x "x on an English Windows version. n on a French one
endif

set backspace=indent,eol,start
set scrolloff=3
set visualbell
set ttyfast
set cursorline
set ruler
set number
set laststatus=2
nnoremap <tab> %
vnoremap <tab> %



nnoremap <leader>d :NERDTreeToggle<cr>

set wildmenu             
set wildmode=longest:full

         
set ignorecase
set smartcase

" Display a place holder character for tabs and trailing spaces
set list
set listchars=trail:·,nbsp:·,tab:>·


" Enable plugins and indentation based on filetype
filetype plugin indent on

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class

nmap <silent> ,/ :nohlsearch<CR>
nnoremap ; :
colorscheme molokai
:set guioptions-=T  "remove toolbar


